#!/bin/bash
#PBS -N inflate_T_only
#PBS -q main
#PBS -l select=1:ncpus=4:ngpus=0:mem=32GB
#PBS -l walltime=00:30:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/inflate_T_only.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/inflate_T_only.err

module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
cd /glade/derecho/scratch/advike/graphcast_recon
python3 inflate_homo_T_only.py
