#!/bin/bash
#PBS -N kernel_val_compare
#PBS -q main
#PBS -l select=1:ncpus=4:ngpus=1:mem=32GB
#PBS -l walltime=00:20:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/val_compare.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/val_compare.err

module load cuda/12.9.0
module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
cd /glade/derecho/scratch/advike/graphcast_recon
python3 validate_kernel_compare.py
