#!/bin/bash
#PBS -N simple_gnn
#PBS -q main
#PBS -l select=1:ncpus=4:ngpus=1:mem=32GB
#PBS -l walltime=04:00:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/simple_gnn.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/simple_gnn.err

module load cuda/12.9.0
module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
cd /glade/derecho/scratch/advike/graphcast_recon
python3 recon_gnn_simple.py --epochs 2000 --lr 5e-3 --hidden 128 --mesh-rounds 6 
