#!/bin/bash
#PBS -N plot_emb
#PBS -q main
#PBS -l select=1:ncpus=4:mem=32GB
#PBS -l walltime=00:30:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/plot_emb.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/plot_emb.err

module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
cd /glade/derecho/scratch/advike/graphcast_recon
python3 plot_summary_emb.py
python3 plot_spatial_trends_emb.py
