#!/bin/bash
#PBS -N plot_homo_T_inf
#PBS -q main
#PBS -l select=1:ncpus=4:ngpus=0:mem=32GB
#PBS -l walltime=01:00:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/plot_homo_T_inflated.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/plot_homo_T_inflated.err

module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
cd /glade/derecho/scratch/advike/graphcast_recon
python3 plot_summary_homo_T_inflated.py
python3 plot_spatial_trends_homo_T_inflated.py
