#!/bin/bash
#PBS -N replot_smb
#PBS -q main
#PBS -l select=1:ncpus=4:mem=32GB
#PBS -l walltime=00:20:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/replot_smb.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/replot_smb.err

module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
cd /glade/derecho/scratch/advike/graphcast_recon
python3 plot_spatial_trends_emb_T_inflated.py
python3 plot_spatial_trends_emb_interp_T_inflated.py
