#!/bin/bash
#PBS -N era5_targets_1
#PBS -A P93300301
#PBS -q main
#PBS -l select=1:ncpus=4:ngpus=0:mem=32GB
#PBS -l walltime=12:00:00
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/targets_1979_1988.log
#PBS -j oe

module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast

cd /glade/derecho/scratch/advike/graphcast_recon
for year in $(seq 1979 1988); do
    python3 era5_targets.py --year $year
done
