#!/bin/bash
#PBS -N apply_recon
#PBS -q main
#PBS -l select=1:ncpus=8:ngpus=1:mem=64GB
#PBS -l walltime=12:00:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/apply.out
#PBS -e /glade/derecho/scratch/advike/graphcast_recon/logs/apply.err

cd /glade/derecho/scratch/advike/graphcast_recon

module load cuda/12.9.0 && module load conda/latest
source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast
python apply.py --all
