#!/bin/bash
#PBS -N graphcast_embed_1979
#PBS -q main
#PBS -l select=1:ncpus=8:ngpus=1:mem=64GB
#PBS -l walltime=06:00:00
#PBS -A P93300301
#PBS -l job_priority=premium
#PBS -j oe
#PBS -o /glade/derecho/scratch/advike/graphcast_recon/logs/embed_1979.log

module load cuda/12.9.0
module load conda/latest

source $(conda info --base)/etc/profile.d/conda.sh
conda activate graphcast

cd /glade/derecho/scratch/advike/graphcast_recon
python3 extract_embeddings.py --year 1979
